name: YT Build
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "22"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Getting Tools
        run: |
          sudo apt install wget curl
          wget https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar
          wget https://github.com/ReVanced/revanced-patches/releases/download/v5.6.0-dev.3/patches-5.6.0-dev.3.rvp
          wget https://github.com/ToothIsSweet/YT/raw/main/ytmg.apk
          wget https://github.com/tanishqmanuja/apkmirror-downloader/releases/download/v1.0.4/apkmd
          chmod 777 apkmd
          ./apkmd apps.json

      - name: Start building YT
        run: |
          java -jar revanced-cli-5.0.0-all.jar \
            patch -p patches-5.6.0-dev.3.rvp \
            -d "Announcements" \
            -d "Downloads" \
            ./downloads/yt.apk
          
      - name: Start building YTM
        run: |
          java -jar revanced-cli-5.0.0-all.jar \
            patch -p patches-5.6.0-dev.3.rvp \
            ./downloads/ytm.apk
          
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./yt*.apk
          release_name: YT Automated Build
          file_glob: true
          overwrite: true
